name = "cafe-search"
main = ".open-next/cloudflare/worker.js"
type = "javascript"
compatibility_date = "2025-11-16"
# Enable `wrangler dev` so you can preview the OpenNext worker locally.
workers_dev = true

pages_build_output_dir = ".open-next/cloudflare"

[build]
command = "npm run build:cloudflare"

[vars]
NODE_ENV = "production"
